### ISSUE TITLE
 "fix(domain): remove int constraint on proxy id"  bug

### ISSUE THREAD

**Issue by ullmannsven** [Kitware/trame-simput#12]
commit [c8cf5bd] where the int constraint on proxy id was removed causes strange behavior, because if the variable 
`domains`, it somehow still passes the `if ` statement.

**Comment by jourdain** [comment]
Could you provide more context on what you are doing and how to highlight those strange behaviors? Are you making your own application or using an exiting application?

**Comment by jourdain** [comment]
Could you provide more context on what you are doing and how to highlight those strange behaviors? Are you making your own application or using an exiting application?

**Comment by ullmannsven** [comment]
We were building our own application together with kitware (mostly @DavidBerger98). The variable `domains` can be undefined in our usecase. Then the `if ` statement is considered to be `True` (this seems strange to me, but this is how it works in python apparently. 

If the int constraint is included, the `if` statement is not passed anymore and everything works fine for our usecase. 

I included a screenshot of the error we get when the int constraint gets removed
![trame_simput_issue](https://user-images.githubusercontent.com/84276962/208441376-64478822-a51b-435a-84d3-e975f1de5383.png)

**Comment by jourdain** [comment]
Thanks for providing more input on that issue. Could you print that value for `domains`? I'm still curious what it is and indeed why the if is going through.

**Comment by ullmannsven** [comment]
My outcome of the print statement is "undefined" (see line 6 in the output)
![trame_simput_issue_domain_value](https://user-images.githubusercontent.com/84276962/208517257-e19a3ad5-a59d-45a6-b6f1-ab7f3443643d.png)
