### ISSUE TITLE
Example: Switch between basic/advanced view

### ISSUE THREAD

**Issue by DavidBerger98** [Kitware/trame-simput#4]
Would be cool to have a simple example of how to implement a button that toggles between a basic and an advanced view, where the advanced view shows a superset of the basic options.

Will probably look similar to how it was implemented in paraview-visualizer with domains. See changing the ClipType of the clip filter.

**Comment by jourdain** [comment]
We could even think of tags rather than just basic/advanced in that simple example.

**Comment by DavidBerger98** [comment]
Closed by #5 and https://github.com/Kitware/trame-simput/commit/1d5de80a8d406362e00422fa41dee8b589cce4b2
